server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: fitlife-api

  datasource:
    url: jdbc:mysql://localhost:3306/fitlife_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate # 1. TƯỚC QUYỀN HIBERNATE (Chỉ cho phép kiểm tra, KHÔNG tạo bảng)

    flyway:
      enabled: true              # 2. BẬT FLYWAY
      baseline-on-migrate: true  # 3. CHẤP NHẬN BASELINE

cloudinary:
  cloud-name: dvseaoy5k
  api-key: 548378961766311
  api-secret: GqtAOdXDUzX9sY5Eqg6LWrb_oKU