services:
  mysql-db:
    image: mysql:8.0
    container_name: fitlife-db-container
    restart: always
    environment:
      MYSQL_DATABASE: fitlife_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - fitlife_mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  fitlife_mysql_data: